name: Branch build

on:
  push:
    branches:
      - revent-gc-shader-ci
    paths-ignore:
      - '.github/**'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-msvc:
    uses: ./.github/workflows/build-msvc-new.yml

  build-msvc-avx2:
    uses: ./.github/workflows/build-msvc-new.yml
    with:
      simd: avx2
      GL: true
      contract-fp: true

  build-mingw:
    uses: ./.github/workflows/build-mingw-new.yml

  #Fallback if compile failed
  fail-msvc:
     needs: [build-msvc]
     if: failure()
     uses: ./.github/workflows/build-msvc-new.yml
     with:
       runos: windows-2019

  fail-msvc-avx2:
     needs: [build-msvc-avx2]
     if: failure()
     uses: ./.github/workflows/build-msvc-new.yml
     with:
       runos: windows-2019
       simd: avx2
       GL: true
       contract-fp: true
