name: Branch build

on:
  push:
    branches:
      - revent-gc-shader-ci
    paths-ignore:
      - '.github/**'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-msvc:
    uses: ./.github/workflows/build-msvc-new.yml

  build-mingw:
    uses: ./.github/workflows/build-mingw-new.yml
