name: Branch build

on:
  push:
    branches:
      - fix-audio-clicking
    paths-ignore:
      - '.github/**'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-msvc:
    uses: ./.github/workflows/build-msvc-cache.yml
    with:
      runos: windows-2019

  build-msvc-avx2:
    uses: ./.github/workflows/build-msvc-cache.yml
    with:
      runos: windows-2019
      simd: avx2
      GL: true
      contract-fp: true
      cache: false
      suffix: '-avx2'

  build-mingw-clang:
    uses: ./.github/workflows/build-mingw-linux.yml

  build-mingw-clang-avx2:
    uses: ./.github/workflows/build-mingw-linux.yml
    with:
      flag: '-O3 -march=znver1 -mtune=znver1'
      suffix: '-o'

  build-mingw-gcc:
    uses: ./.github/workflows/build-mingw-linux.yml
    with:
      compiler: 'gcc'

  build-mingw-gcc-avx2:
    uses: ./.github/workflows/build-mingw-linux.yml
    with:
      compiler: 'gcc'
      flag: '-O3 -march=znver1'
      suffix: '-o'

  #Fallback if compile failed
# fail-msvc:
#    needs: [build-msvc]
#    if: failure()
#    uses: ./.github/workflows/build-msvc-new.yml
#    with:
#      runos: windows-2019

# fail-msvc-avx2:
#    needs: [build-msvc-avx2]
#    if: failure()
#    uses: ./.github/workflows/build-msvc-new.yml
#    with:
#      runos: windows-2019
#      simd: avx2
#      GL: true
#      contract-fp: true
