name: Branch build

on:
  push:
    branches:
      - fix-audio-clicking
    paths-ignore:
      - '.github/**'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-msvc:
    uses: ./.github/workflows/build-msvc-cache.yml
    with:
      runos: windows-2019

  build-msvc-avx2:
    uses: ./.github/workflows/build-msvc-cache.yml
    with:
      runos: windows-2019
      simd: avx2
      GL: true
      contract-fp: true
      cache: false
      suffix: '-avx2'

  build-mingw-clang:
    uses: ./.github/workflows/build-mingw-linux.yml

  build-mingw-clang-avx2:
    uses: ./.github/workflows/build-mingw-linux.yml
    with:
      flag: '-O3 -march=znver1 -mtune=znver1'
      suffix: '-o'

  build-mingw-clang-polly:
    uses: ./.github/workflows/build-mingw-linux.yml
    with:
      polly: true
      flag: '-Xclang -fpass-plugin=LLVMPolly.so -Ofast -march=znver1 -mtune=znver1 -DFLOAT_APPROX=1 -mllvm -polly -mllvm -polly-vectorizer=stripmine -mllvm -polly-ast-use-context -mllvm -polly-invariant-load-hoisting -mllvm -polly-loopfusion-greedy -mllvm -polly-run-inliner -mllvm -polly-run-dce'
      suffix: '-o-polly-fast'

  build-mingw-gcc:
    uses: ./.github/workflows/build-mingw-linux.yml
    with:
      compiler: 'gcc'

  build-mingw-gcc-avx2:
    uses: ./.github/workflows/build-mingw-linux.yml
    with:
      compiler: 'gcc'
      flag: '-O3 -march=znver1'
      suffix: '-o'

  #Fallback if compile failed
# fail-msvc:
#    needs: [build-msvc]
#    if: failure()
#    uses: ./.github/workflows/build-msvc-new.yml
#    with:
#      runos: windows-2019

# fail-msvc-avx2:
#    needs: [build-msvc-avx2]
#    if: failure()
#    uses: ./.github/workflows/build-msvc-new.yml
#    with:
#      runos: windows-2019
#      simd: avx2
#      GL: true
#      contract-fp: true
