name: yuzu Build MSVC (cache)

on:
  workflow_call:
    inputs:
      runos:
        description: 'Running operating system. Which will change VS version.'
        type: string
        required: false
        default: 'windows-latest'
      simd:
        description: 'Compiler instruction set. Can be avx, avx2.'
        type: string
        required: false
        default: ''
      GL:
        description: 'Enables whole program optimization.This will enable LTCG.'
        type: boolean
        required: false
        default: false
      contract-fp:
        description: 'Allows the compiler to generate floating-point contractions.'
        type: boolean
        required: false
        default: false
      type-fp:
        description: 'Type of floating-point behavior.Can be default, fast(unsafe), precise, strict'
        type: string
        required: false
        default: 'default'

  workflow_dispatch:
    inputs:
      runos:
        description: 'Running operating system. Which will change VS version.'
        type: choice
        required: false
        options:
        - windows-latest
        - windows-2019
      simd:
        description: 'Compiler instruction set. Can be avx, avx2.'
        type: string
        required: false
        default: ''
      GL:
        description: 'Enables whole program optimization.This will enable LTCG.'
        type: boolean
        required: false
        default: false
      contract-fp:
        description: 'Allows the compiler to generate floating-point contractions.'
        type: boolean
        required: false
        default: false
      type-fp:
        description: 'Type of floating-point behavior.Can be default, fast(unsafe), precise, strict'
        type: string
        required: false
        default: 'default'

jobs:
  build:
    name: Building yuzu Binaries with MSVC (cache)
    runs-on: ${{ (inputs || github.event.inputs).runos }}
#   env:
#     VCPKG_TOOLCHAIN_FILE: "${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake"
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: actions/checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      #Generate submodules list
      - name: Generate submodules list
        run: |
          git submodule > modulehash.txt && echo Completed
          echo Completed
        shell: cmd

      #Set short SHA
      - name: Set short SHA outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)" && echo Completed
        shell: pwsh

      #Setup vcpkg
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 'cef0b3ec767df6e83806899fe9525f6cf8d7bc91'
          runVcpkgInstall: true
          vcpkgJsonGlob: './vcpkg.json'
          appendedCacheKey: ${{ (inputs || github.event.inputs).runos }}-vcpkg-msvc

      #Install Vulkan SDK
      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.211.0
          vulkan-components: Vulkan-Headers, Glslang
          vulkan-use-cache: true

      #Install CMake
      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      #Set extansion compiler arguments
      - name: Set extansion compiler arguments
#       if: ${{ (inputs || github.event.inputs).simd != '' }}
        run: |
          os=${{ (inputs || github.event.inputs).runos }}
          simd=${{ (inputs || github.event.inputs).simd }}
          gl=${{ (inputs || github.event.inputs).GL }}
          fpc=${{ (inputs || github.event.inputs).contract-fp }}
          fpt=${{ (inputs || github.event.inputs).type-fp }}
          comp_args_cxx="/DWIN32 /D_WINDOWS /GR /EHsc "
          comp_args_c="/DWIN32 /D_WINDOWS "
          link_args="/machine:x64 "
          cmake_args="-GNinja"
          bsuffix=""
          if [ "$os" == "windows-latest" ]
          then
              bsuffix=$bsuffix"-vs2022"
          elif [ "$os" == "windows-2019" ]
          then
              bsuffix=$bsuffix"-vs2019"
          fi
          if [ "$gl" == "True" ] || [ "$gl" == "true" ]
          then
              comp_args_cxx=$comp_args_cxx"/GL "
              comp_args_c=$comp_args_c"/GL "
              link_args=$link_args"/LTCG "
          fi
          if [ "$fpc" == "True" ] || [ "$fpc" == "true" ] && [ "$os" == "windows-latest" ]
          then
              comp_args_cxx=$comp_args_cxx"/fp:contract "
              comp_args_c=$comp_args_c"/fp:contract "
          fi
          if [ "$fpt" == "fast" ]
          then
              comp_args_cxx=$comp_args_cxx"/fp:fast "
              comp_args_c=$comp_args_c"/fp:fast "
          elif [ "$fpt" == "precise" ]
          then
              comp_args_cxx=$comp_args_cxx"/fp:precise "
              comp_args_c=$comp_args_c"/fp:precise "
          elif [ "$fpt" == "strict" ]
          then
              comp_args_cxx=$comp_args_cxx"/fp:strict "
              comp_args_c=$comp_args_c"/fp:strict "
          fi
          if [ "$simd" = "AVX" ] || [ "$simd" = "avx" ]
          then
              comp_args_cxx=$comp_args_cxx"/arch:AVX "
              comp_args_c=$comp_args_c"/arch:AVX "
              bsuffix=$bsuffix"-avx"
          elif [ "$simd" = "AVX2" ] || [ "$simd" = "avx2" ]
          then
              comp_args_cxx=$comp_args_cxx"/arch:AVX2 "
              comp_args_c=$comp_args_c"/arch:AVX2 "
              bsuffix=$bsuffix"-avx2"
          elif [ "$simd" = "" ]
          then
              echo ''
          else
              echo 'Unknown instruction set' $simd
          fi
          echo 'build-gen='$cmake_args >> $GITHUB_ENV
          echo 'build-arg-ext=-DCMAKE_CXX_FLAGS="'$comp_args_cxx'"' '-DCMAKE_C_FLAGS="'$comp_args_c'"' '-DCMAKE_EXE_LINKER_FLAGS="'$link_args'"' >> $GITHUB_ENV
          echo 'simd-suffix='$bsuffix >> $GITHUB_ENV
        shell: bash
        
      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: ~/.buildcache
          key: ${{ runner.os }}-${{ env.simd-suffix }}-msvc-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ env.simd-suffix }}-msvc-

      - name: Install buildcache
        run: |
          choco install wget
          call refreshenv
          wget https://github.com/mbitsnbites/buildcache/releases/download/v0.27.6/buildcache-windows.zip
          7z x buildcache-windows.zip
          copy buildcache\bin\buildcache.exe C:\ProgramData\chocolatey\bin
          rmdir buildcache
          echo %PATH% >> %GITHUB_PATH%
        shell: cmd

      #Preparing Build
      - name: Before Build
        env:
          build-arg: -DCMAKE_TOOLCHAIN_FILE="CMakeModules/MSVCCache.cmake" -DUSE_CCACHE=ON -DYUZU_USE_BUNDLED_VCPKG=OFF -DYUZU_USE_BUNDLED_QT=1 -DYUZU_USE_BUNDLED_SDL2=1 -DYUZU_USE_QT_WEB_ENGINE=ON -DYUZU_TESTS=OFF -DUSE_DISCORD_PRESENCE=ON -DTITLE_BAR_FORMAT_IDLE="yuzu Early Access ${{ github.ref_name }}-${{ steps.vars.outputs.sha_short }}" -DTITLE_BAR_FORMAT_RUNNING="yuzu Early Access ${{ github.ref_name }}-${{ steps.vars.outputs.sha_short }} | {3}" -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=ON -DENABLE_QT_TRANSLATION=ON -DCMAKE_BUILD_TYPE=Release
          CC: cl.exe
          CXX: cl.exe
        run: |
          mkdir build && cd build
          cmake --version
          cmake .. ${{ env.build-gen }} ${{ env.build-arg }} ${{ env.build-arg-ext }}
        shell: pwsh

      #Build the .sln
      - name: Build app for release
        run: cmake --build build

      - name: After Build
        run: |
          buildcache -s
          mkdir ${{ github.workspace }}\build\bin\yuzu-build\yuzu-${{ steps.vars.outputs.sha_short }}-msvc
          mv ${{ github.workspace }}\build\bin\Release\* ${{ github.workspace }}\build\bin\yuzu-build\yuzu-${{ steps.vars.outputs.sha_short }}-msvc
          del ${{ github.workspace }}\build\bin\yuzu-build\yuzu-${{ steps.vars.outputs.sha_short }}-msvc\*.pdb
        shell: pwsh

      - name: Compress the Build Folder
        run: |
          7z a -t7z "yuzu-ea-${{ github.ref_name }}-${{ steps.vars.outputs.sha_short }}-msvc${{ env.simd-suffix }}.7z" -m0=lzma2:d=64m -mx=9 -aoa -mfb=64 -md=32m -ms=on "${{ github.workspace }}\build\bin\yuzu-build"
        shell: pwsh
          
      #Upload Artifacts
      - name: Making artifact
        uses: actions/upload-artifact@v2
        with:
          name: yuzu-ea-${{ steps.vars.outputs.sha_short }}-msvc${{ env.simd-suffix }}
          path: yuzu-ea-${{ github.ref_name }}-${{ steps.vars.outputs.sha_short }}-msvc${{ env.simd-suffix }}.7z
          retention-days: 7

