name: yuzu Build Android
on:
  workflow_call:

  workflow_dispatch:

jobs:
  build:
    name: Building yuzu Binaries
    runs-on: ubuntu-latest
    env:
      BUILD_FLAVOR: "kpatch"
    steps:
      - name: actions/checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Query tag name
        uses: olegtarasov/get-tag@v2.1.2
        id: tagName
      - name: Set environment variables
        run: |
          echo GITREV=$(git rev-parse --short HEAD) >> $GITHUB_ENV
          echo GITDATE=$(date +%Y%m%d) >> $GITHUB_ENV
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache apksigner glslang-dev glslang-tools
          git -C ./externals/vcpkg/ fetch --all --unshallow
      - name: Build
        run: |
          cd src/android
          vim ./gradlew -c "set ff=unix" -c ":x"
          chmod +x ./gradlew
          ./gradlew "assemble${BUILD_FLAVOR}Release" "bundle${BUILD_FLAVOR}Release"
      - name: Copy and sign artifacts
        env:
          ANDROID_KEYSTORE_B64: ${{ secrets.ANDROID_KEYSTORE_B64 }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEYSTORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASS }}
        run: |
          REV_NAME="yuzu-${GITDATE}-${GITREV}"
          mkdir ./artifacts
          cp src/android/app/build/outputs/apk/"${BUILD_FLAVOR}/release/app-${BUILD_FLAVOR}-release.apk" "artifacts/${REV_NAME}.apk"
          cp src/android/app/build/outputs/bundle/"${BUILD_FLAVOR}Release"/"app-${BUILD_FLAVOR}-release.aab" "artifacts/${REV_NAME}.aab"
          echo "Signing apk..."
          base64 --decode <<< "${ANDROID_KEYSTORE_B64}" > ks.jks
          apksigner sign --v1-signing-enabled false --v2-signing-enabled false --ks ks.jks --ks-key-alias "${ANDROID_KEY_ALIAS}" --ks-pass env:ANDROID_KEYSTORE_PASS "artifacts/${REV_NAME}.apk"
          echo "Downloading bundletool..."
          curl -s https://api.github.com/repos/google/bundletool/releases/latest \
          | grep "browser_download_url.*jar" \
          | cut -d : -f 2,3 \
          | tr -d \" \
          | wget -qi -
          echo "Extracting aab..."
          mv bundletool*.jar bundletool.jar
          java -jar bundletool.jar build-apks --bundle=./artifacts/${REV_NAME}.aab --output=./artifacts/${REV_NAME}.apks --ks=ks.jks --ks-pass=pass:${ANDROID_KEYSTORE_PASS} --ks-key-alias=${ANDROID_KEY_ALIAS} --mode=universal
      - name: Compress the Build Folder
        run: |
          7z a -t7z "yuzu-ea-${{ github.ref_name }}-${GITREV}-android.7z" -m0=lzma2:d=64m -mx=9 -aoa -mfb=64 -md=32m -ms=on "./artifacts/*.apk" "./artifacts/*.idsig"
          7z a -t7z "yuzu-ea-${{ github.ref_name }}-${GITREV}-android-apks.7z" -m0=lzma2:d=64m -mx=9 -aoa -mfb=64 -md=32m -ms=on "./artifacts/*.apks"
      - name: Making artifact
        uses: actions/upload-artifact@v3
        with:
          name: yuzu-ea-${{ env.GITREV }}-android
          path: yuzu-ea-${{ github.ref_name }}-${{ env.GITREV }}-android.7z
          retention-days: 7
      - name: Making artifact
        uses: actions/upload-artifact@v3
        with:
          name: yuzu-ea-${{ env.GITREV }}-android-apks
          path: yuzu-ea-${{ github.ref_name }}-${{ env.GITREV }}-android-apks.7z
          retention-days: 7
