name: Auto check update

on:
# push:
#   branches:
#     - early-access

  schedule:
    - cron: "5 */3 * * *"

  workflow_dispatch:

jobs:
  build:
    name: Checking update
    if: ${{ github.ref_name == 'early-access' }}
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: actions/checkout
        uses: actions/checkout@v3
        with:
          path: './current'
          ref : ${{ github.head_ref }}
          token : ${{ secrets.PAT }}

      - name: Cloneing upstream repository
        uses: actions/checkout@v3
        with:
          repository: 'pineappleEA/pineapple-src'
          path: './upstream-pinapple'

      - name: Fetch upstream tags
        run: |
          cd upstream-pinapple
          git fetch --tags origin

      - name: Downloading upstream repository release
        uses: robinraju/release-downloader@v1.7
        with:
          repository: 'pineappleEA/pineapple-src'
          latest: true
          fileName: '*.zip'

      - name: Extracting files
        run: |
          mkdir temp && cd temp
          7z e ../*.zip -o. "*/*.tar.xz"
          7z x -y *.tar.xz
          7z x -y *.tar -o./exted
          mkdir ../upstream-pinapple-src
          mv -f ./exted/*/* ../upstream-pinapple-src

      - name: Copy to current repository
        run: |
          rsync -rlcih --size-only --progress --stats --exclude='README.md' --exclude='.gitattributes' --exclude='.gitignore' --exclude='.git/' --exclude='.github/' --exclude='vcpkg.json' --exclude='license.txt' --exclude='.gitattributes' --exclude='lgtm.yml' --exclude='.gitmodules' --exclude='.ci/' --exclude='.reuse/' --exclude='patches/' --delete ./upstream-pinapple-src/ ./current

      - name: Get current day
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Get Early access number
        id: eaver
        run: |
          cd upstream-pinapple
          commit="$(git rev-list --tags --max-count=1)"
          echo "ver=$(git describe --tags $commit)" >> $GITHUB_OUTPUT

      - name: Commit to remote
        uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit-action
        with: 
          repository: ./current
          commit_message: Automated Change at ${{ steps.date.outputs.date }}
          commit_options: '-m "${{ steps.eaver.outputs.ver }}"'
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          tagging_message: '${{ steps.eaver.outputs.ver }}'

      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes! Commit hash ${{ steps.auto-commit-action.outputs.commit_hash }}"

      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "Nothing Changes!"
