name: Automatic Rebase

on:
  push:
    tags:
      - '**'

  workflow_dispatch:

jobs:
  rebase:
    name: Automatic Rebase
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2
        with:
          token : ${{ secrets.PAT }}

      - name: ReSync Branch
        run: |
          git remote set-url --push origin https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git
          git remote update
          git fetch
          git checkout test-auto-commit
          git rebase ${{github.event.repository.default_branch}}
          git push origin test-auto-commit --force

#     - name: ReSync Branch
#       uses: Joao208/resync-branch@1.5.0
#       with:
#         PERSONAL_TOKEN: ${{ secrets.PAT }}
#         BRANCH_NAME: test-auto-commit
#         DEFAULT_BRANCH: ${{github.event.repository.default_branch}}