name: Automatic Rebase

on:
  push:
    tags:
      - '**'

  workflow_dispatch:

jobs:
  rebase:
    name: Automatic Rebase
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2
        with:
          token : ${{ secrets.PAT }}
          fetch-depth: 0

      - name: ReSync Branch
        if: ${{ github.ref_type == 'branch' }}
        run: |
          git remote set-url --push origin https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git branch
          git checkout revent-gc-shader-ci
          git rebase ${{github.event.repository.default_branch}}
          git push origin revent-gc-shader-ci --force

      - name: ReSync Branch (tag)
        if: ${{ github.ref_type == 'tag' }}
        run: |
          git remote set-url --push origin https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout ${{github.event.repository.default_branch}}
          git branch
          git checkout revent-gc-shader-ci
          git rebase ${{github.event.repository.default_branch}}
          git push origin revent-gc-shader-ci --force

#     - name: ReSync Branch
#       uses: Joao208/resync-branch@1.5.0
#       with:
#         PERSONAL_TOKEN: ${{ secrets.PAT }}
#         BRANCH_NAME: test-auto-commit
#         DEFAULT_BRANCH: ${{github.event.repository.default_branch}}
